---
sidebar: sidebar 
permalink: trident-docker/known-issues-docker.html 
keywords: known issues, trident, trident for docker, docker 
summary: Trova informazioni sui problemi noti quando si utilizza Trident con Docker. 
---
= Problemi e limitazioni noti
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trova informazioni sui problemi noti e sulle limitazioni quando si utilizza Trident con Docker.



== L'aggiornamento di Trident Docker Volume Plugin alla versione 20.10 e successive da versioni precedenti provoca un errore di aggiornamento con l'errore no such file or directory.

.Soluzione alternativa
. Disattiva il plugin.
+
[source, console]
----
docker plugin disable -f netapp:latest
----
. Rimuovi il plugin.
+
[source, console]
----
docker plugin rm -f netapp:latest
----
. Reinstallare il plugin fornendo il parametro extra `config`.
+
[source, console]
----
docker plugin install netapp/trident-plugin:20.10 --alias netapp --grant-all-permissions config=config.json
----




== I nomi dei volumi devono essere lunghi almeno 2 caratteri.


NOTE: Si tratta di una limitazione del client Docker. Il client interpreterà un nome a carattere singolo come un percorso di Windows. https://github.com/moby/moby/issues/25773["Vedi bug 25773"^]



== Docker Swarm ha alcuni comportamenti che impediscono a Trident di supportarlo con ogni combinazione di storage e driver.

* Attualmente Docker Swarm utilizza il nome del volume invece dell'ID del volume come identificatore univoco del volume.
* Le richieste di volume vengono inviate simultaneamente a ogni nodo di un cluster Swarm.
* I plugin di volume (incluso Trident) devono essere eseguiti in modo indipendente su ogni nodo di un cluster Swarm. A causa del modo in cui ONTAP funziona e di come i driver `ontap-nas` e `ontap-san` funzionano, sono gli unici che possono operare entro queste limitazioni.


Il resto dei driver è soggetto a problemi come le race condition che possono portare alla creazione di un gran numero di volumi per una singola richiesta senza un chiaro "winner"; ad esempio, Element ha una funzione che consente ai volumi di avere lo stesso nome ma ID diversi.

NetApp ha fornito feedback al team Docker, ma non ha alcuna indicazione su eventuali azioni future.



== Se è in corso il provisioning di un FlexGroup, ONTAP non esegue il provisioning di un secondo FlexGroup se il secondo FlexGroup ha uno o più aggregati in comune con il FlexGroup in fase di provisioning.
