---
sidebar: sidebar 
permalink: trident-docker/multiple-instances-docker.html 
keywords: deploy, Trident, docker, trident for docker, managed plugin, trident instances, alias 
summary: 'Le istanze multiple di Trident sono necessarie quando si desidera avere più configurazioni di storage disponibili simultaneamente. La chiave per le istanze multiple è assegnare loro nomi diversi utilizzando l"opzione --alias con il plugin containerizzato o l"opzione --volume-driver quando si istanzia Trident sull"host.' 
---
= Gestisci più istanze di Trident
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le istanze multiple di Trident sono necessarie quando si desidera avere più configurazioni di storage disponibili simultaneamente. La chiave per le istanze multiple è assegnare loro nomi diversi usando l' `--alias` opzione con il plugin containerizzato, o l' `--volume-driver` opzione quando si istanzia Trident sull'host.



== Passaggi per il plugin gestito da Docker (versione 1.13/17.03 o successiva)

. Avvia la prima istanza specificando un alias e il file di configurazione.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias silver netapp/trident-plugin:21.07 config=silver.json
----
. Avvia la seconda istanza, specificando un alias diverso e il file di configurazione.
+
[source, console]
----
docker plugin install --grant-all-permissions --alias gold netapp/trident-plugin:21.07 config=gold.json
----
. Crea volumi specificando l'alias come nome del driver.
+
Ad esempio, per il volume gold:

+
[source, console]
----
docker volume create -d gold --name ntapGold
----
+
Ad esempio, per il volume silver:

+
[source, console]
----
docker volume create -d silver --name ntapSilver
----




== Passaggi per il tradizionale (versione 1.12 o precedente)

. Avvia il plugin con una configurazione NFS utilizzando un ID driver personalizzato:
+
[source, console]
----
sudo trident --volume-driver=netapp-nas --config=/path/to/config-nfs.json
----
. Avvia il plugin con una configurazione iSCSI utilizzando un driver ID personalizzato:
+
[source, console]
----
sudo trident --volume-driver=netapp-san --config=/path/to/config-iscsi.json
----
. Effettua il provisioning dei volumi Docker per ogni istanza del driver:
+
Ad esempio, per NFS:

+
[source, console]
----
docker volume create -d netapp-nas --name my_nfs_vol
----
+
Ad esempio, per iSCSI:

+
[source, console]
----
docker volume create -d netapp-san --name my_iscsi_vol
----

