---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy-tridentctl.html 
keywords: deploy, Trident, methods, operator, tridentctl, helm, attributes, customize 
summary: È possibile utilizzare il programma di installazione Trident per personalizzare la distribuzione. 
---
= Personalizza l'installazione di tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile utilizzare il programma di installazione Trident per personalizzare l'installazione.



== Informazioni sul programma di installazione

Il programma di installazione Trident consente di personalizzare gli attributi. Ad esempio, se hai copiato l'immagine Trident in un repository privato, puoi specificare il nome dell'immagine usando `--trident-image`. Se hai copiato l'immagine Trident e anche le immagini CSI sidecar necessarie in un repository privato, potrebbe essere preferibile specificare la posizione di quel repository usando lo switch `--image-registry`, che assume la forma `<registry FQDN>[:port]`.


IMPORTANT: Quando si installa Trident in un repository privato, se si utilizza l'opzione `--image-registry` per specificare la posizione del repository, non utilizzare `/netapp/` nel percorso del repository. Ad esempio: `./tridentctl install --image-registry <image-registry> -n <namespace>`

Se si utilizza una distribuzione di Kubernetes, dove `kubelet` conserva i dati su un percorso diverso dal solito `/var/lib/kubelet`, è possibile specificare il percorso alternativo utilizzando `--kubelet-dir`.

Se si desidera personalizzare l'installazione al di là di quanto consentito dagli argomenti del programma di installazione, è possibile personalizzare anche i file di deployment. L'utilizzo del parametro `--generate-custom-yaml` crea i seguenti file YAML nella directory del programma di installazione `setup`:

* `trident-clusterrolebinding.yaml`
* `trident-deployment.yaml`
* `trident-crds.yaml`
* `trident-clusterrole.yaml`
* `trident-daemonset.yaml`
* `trident-service.yaml`
* `trident-namespace.yaml`
* `trident-serviceaccount.yaml`
* `trident-resourcequota.yaml` *


Dopo aver generato questi file, puoi modificarli secondo le tue esigenze e poi usare `--use-custom-yaml` per installare la tua distribuzione personalizzata.

[source, console]
----
./tridentctl install -n trident --use-custom-yaml
----