---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-tridentctl.html 
keywords: deploy, Trident, methods, tridentctl, windows 
summary: 'È possibile installare Trident utilizzando `tridentctl`. Questa procedura si applica alle installazioni in cui le immagini dei container richieste da Trident sono archiviate in un registro privato o meno.' 
---
= Installare utilizzando tridentctl
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile installare Trident usando  `tridentctl`. Questa procedura si applica alle installazioni in cui le immagini dei container richieste da Trident sono archiviate sia in un registro privato che no. Per personalizzare la tua  `tridentctl` distribuzione, fare riferimento a link:kubernetes-customize-deploy-tridentctl.html["Personalizza la distribuzione di tridentctl"].



== Informazioni critiche su Trident10

*È necessario leggere le seguenti informazioni critiche su Trident.*

.<strong>Informazioni critiche su Trident</strong>
[%collapsible%open]
====
* Kubernetes 1.27 è ora supportato in Trident. Aggiornare Trident prima di aggiornare Kubernetes.
* Trident impone rigorosamente l'uso della configurazione multipathing negli ambienti SAN, con un valore consigliato di  `find_multipaths: no` nel file multipath.conf.
+
L'utilizzo di una configurazione non multipath o l'utilizzo di  `find_multipaths: yes` o  `find_multipaths: smart` nel file multipath.conf causerà errori di montaggio. Trident ha raccomandato l'utilizzo di  `find_multipaths: no` dalla release 21.07.



====


== Installa Trident usando `tridentctl`

Verificate link:../trident-get-started/kubernetes-deploy.html["la panoramica dell'installazione"] per assicurarvi di aver soddisfatto i prerequisiti di installazione e di aver selezionato l'opzione di installazione corretta per il vostro ambiente.

.Prima di iniziare
Prima di iniziare l'installazione, accedi all'host Linux e verifica che stia gestendo un link:requirements.html["cluster Kubernetes supportato"^] funzionante e che tu disponga dei privilegi necessari.


NOTE: Con OpenShift, utilizzare  `oc` invece di  `kubectl` in tutti gli esempi che seguono e accedere prima come *system:admin* eseguendo  `oc login -u system:admin` o  `oc login -u kube-admin`.

[%collapsible%open]
====
. Verifica la versione di Kubernetes:
+
[listing]
----
kubectl version
----
. Verificare i privilegi di amministratore del cluster:
+
[listing]
----
kubectl auth can-i '*' '*' --all-namespaces
----
. Verifica di poter avviare un pod che utilizza un'immagine da Docker Hub e raggiungere il tuo sistema storage tramite la rete del pod:
+
[listing]
----
kubectl run -i --tty ping --image=busybox --restart=Never --rm -- \
  ping <management IP>
----


====


== Passaggio 1: Scarica il pacchetto di installazione di Trident

Il pacchetto di installazione di Trident crea un pod Trident, configura gli oggetti CRD utilizzati per mantenerne lo stato e inizializza i sidecar CSI per eseguire azioni come il provisioning e il collegamento di volumi agli host del cluster. Scarica ed estrai la versione più recente del programma di installazione di Trident da link:https://github.com/NetApp/trident/releases/latest["la sezione _Assets_ su GitHub"^]. Aggiorna _<trident-installer-XX.XX.X.tar.gz>_ nell'esempio con la versione di Trident selezionata.

[listing]
----
wget https://github.com/NetApp/trident/releases/download/v25.10.0/trident-installer-25.10.0.tar.gz
tar -xf trident-installer-25.10.0.tar.gz
cd trident-installer
----


== Passaggio 2: installa Trident

Installa Trident nello spazio dei nomi desiderato eseguendo il  `tridentctl install` comando. Puoi aggiungere argomenti aggiuntivi per specificare la posizione del registro delle immagini.

[role="tabbed-block"]
====
.Modalità standard
--
[listing]
----
./tridentctl install -n trident
----
--
.Immagini in un registry
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.10 --trident-image <your-registry>/trident:25.10.0
----
--
.Immagini in diversi registri
--
[listing]
----
./tridentctl install -n trident --image-registry <your-registry> --autosupport-image <your-registry>/trident-autosupport:25.10 --trident-image <your-registry>/trident:25.10.0
----
--
====
Lo stato dell'installazione dovrebbe essere simile a questo.

[listing]
----
....
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-controller-679648bd45-cv2mx
INFO Waiting for Trident REST interface.
INFO Trident REST interface is up.                 version=25.10.0
INFO Trident installation succeeded.
....
----


== Verificare l'installazione

Puoi verificare la tua installazione utilizzando lo stato di creazione del pod o `tridentctl`.



=== Utilizzo dello stato di creazione del pod

Puoi confermare se l'installazione di Trident è stata completata esaminando lo stato dei pod creati:

[listing]
----
kubectl get pods -n trident

NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-679648bd45-cv2mx   6/6     Running   0          5m29s
trident-node-linux-vgc8n              2/2     Running   0          5m29s
----

NOTE: Se il programma di installazione non viene completato correttamente o `trident-controller-<generated id>` (`trident-csi-<generated id>` nelle versioni precedenti alla 23.01) non presenta lo stato *Running*, la piattaforma non è stata installata. Usa  `-d` per link:../troubleshooting.html#troubleshooting-an-unsuccessful-trident-deployment-using-tridentctl["attiva la modalità debug"] e risolvere il problema.



=== Utilizzando `tridentctl`

Puoi usare `tridentctl` per verificare la versione di Trident installata.

[listing]
----
./tridentctl -n trident version

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 25.10.0        | 25.10.0        |
+----------------+----------------+
----


== Configurazioni di esempio

Gli esempi seguenti forniscono configurazioni di esempio per l'installazione di Trident usando  `tridentctl`.

.Nodi Windows
[%collapsible]
====
Per abilitare Trident sui nodi Windows:

[listing]
----
tridentctl install --windows -n trident
----
====
.Forza distacco
[%collapsible]
====
Per informazioni, vedere link:../trident-reco/force-detach.html["Automatizzare il failover delle applicazioni stateful con Trident"].

[listing]
----
tridentctl install --enable-force-detach=true -n trident
----
====
.Abilita le operazioni simultanee del controller Trident
[%collapsible]
====
Per abilitare operazioni simultanee del controller Trident per migliorare il throughput, aggiungere l'opzione  `--enable-concurrency` durante l'installazione come mostrato in questo esempio.


NOTE: *Anteprima tecnica*: questa funzionalità è sperimentale e attualmente supporta flussi di lavoro paralleli limitati con i driver ONTAP-NAS (solo NFS) e ONTAP-SAN (NVMe per unified ONTAP 9), oltre all'anteprima tecnica esistente per il driver ONTAP-SAN (protocolli iSCSI e FCP in unified ONTAP 9).

[listing]
----
tridentctl install --enable-concurrency -n trident
----
====