---
sidebar: sidebar 
permalink: trident-get-started/requirements.html 
keywords: trident requirements, supported front ends, supported backends, kubernetes cluster, cluster requirements, version requirements, supported versions, host configuration, host os, system configuration, host operating system, fsx, ports, csi, images, orchestrators, storage systems, feature, kubernetes 
summary: Prima di installare Trident dovresti esaminare questi requisiti generali di sistema. I backend specifici potrebbero avere requisiti aggiuntivi. 
---
= Requisiti
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima di installare Trident dovresti esaminare questi requisiti generali di sistema. I backend specifici potrebbero avere requisiti aggiuntivi.



== Informazioni critiche su Trident

*È necessario leggere le seguenti informazioni critiche su Trident.*

.<strong>Informazioni critiche su Trident</strong>
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34 è ora supportato in Trident. Aggiorna Trident prima di aggiornare Kubernetes.
* Trident impone rigorosamente l'uso della configurazione multipathing negli ambienti SAN, con un valore consigliato di  `find_multipaths: no` nel file multipath.conf.
+
L'utilizzo di una configurazione non multipath o l'utilizzo di  `find_multipaths: yes` o  `find_multipaths: smart` nel file multipath.conf causerà errori di montaggio. Trident ha raccomandato l'utilizzo di  `find_multipaths: no` dalla release 21.07.



=====
====


== Frontend supportati (orchestratori)

Trident supporta più motori di container e orchestratori, tra cui:

* Anthos On-Prem (VMware) e Anthos on bare metal 1.16
* Kubernetes 1.27 - 1.34
* OpenShift 4.12, 4.14 - 4.20 (Se prevedi di utilizzare la preparazione del nodo iSCSI con OpenShift 4.19, la versione minima di Trident supportata è 25.06.1.)
+

NOTE: Trident continua a supportare le versioni precedenti di OpenShift in linea con la link:https://access.redhat.com/support/policy/updates/openshift["Red Hat Extended Update Support (EUS) ciclo di vita"], anche se si basano su versioni di Kubernetes che non sono più ufficialmente supportate upstream. Durante l'installazione di Trident in questi casi, puoi ignorare in tutta sicurezza eventuali messaggi di avviso relativi alla versione di Kubernetes.

* Rancher Kubernetes Engine 2 (RKE2) v1.28.x - 1.34.x
+

NOTE: _Sebbene Trident sia supportato su Rancher Kubernetes Engine 2 (RKE2) versioni 1.27.x - 1.34.x, Trident è attualmente stato qualificato solo su RKE2 v1.28.5+rke2r1._



Trident funziona anche con una serie di altre offerte Kubernetes completamente gestite e autogestite, tra cui Google Kubernetes Engine (GKE), Amazon Elastic Kubernetes Services (EKS), Azure Kubernetes Service (AKS), Mirantis Kubernetes Engine (MKE) e VMWare Tanzu Portfolio.

Trident e ONTAP possono essere utilizzati come provider di storage per link:https://kubevirt.io/["KubeVirt"].


WARNING: Prima di aggiornare un cluster Kubernetes dalla versione 1.25 alla 1.26 o successiva su cui è installato Trident, fare riferimento a link:../trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-installation["Aggiornare un'installazione di Helm"].



== Backend supportati (storage)

Per utilizzare Trident, è necessario uno o più dei seguenti backend supportati:

* Amazon FSx for NetApp ONTAP
* Azure NetApp Files
* Cloud Volumes ONTAP
* Google Cloud NetApp Volumes
* NetApp All SAN Array (ASA)
* FAS, AFF o ASA r2 in locale (iSCSI, NVMe/TCP e FC) che eseguono versioni di ONTAP con NetApp supporto completo o limitato. Vedere link:https://mysupport.netapp.com/site/info/version-support["Supporto della versione software"].
* NetApp HCI/Element software 11 o superiore




== Supporto Trident per KubeVirt e OpenShift Virtualization

.Driver di storage supportati:
Trident supporta i seguenti driver ONTAP per KubeVirt e OpenShift Virtualization:

* ontap-nas
* ontap-nas-economy
* ontap-san (iSCSI, FCP, NVMe over TCP)
* ontap-san-economy (solo iSCSI)


.Punti da considerare:
* Aggiornare la storage class in modo che abbia il  `fsType` parametro (ad esempio:  `fsType: "ext4"`) nell'ambiente OpenShift Virtualization. Se necessario, impostare la modalità volume su block in modo esplicito utilizzando il  `volumeMode=Block` parametro nel  `dataVolumeTemplates` per notificare a CDI di creare volumi di dati Block.
* _Modalità di accesso RWX per driver di storage a blocchi_: i driver ontap-san (iSCSI, NVMe/TCP, FC) e ontap-san-economy (iSCSI) sono supportati solo con "volumeMode: Block" (raw device). Per questi driver, il parametro  `fstype` non può essere utilizzato perché i volumi sono forniti in modalità raw device.
* Per i flussi di lavoro di live-migration in cui è richiesta la modalità di accesso RWX, sono supportate le seguenti combinazioni:
+
** NFS + `volumeMode=Filesystem`
** iSCSI + `volumeMode=Block` (dispositivo raw)
** NVMe/TCP + `volumeMode=Block` (dispositivo raw)
** FC + `volumeMode=Block` (raw dispositivo)






== Requisiti delle funzionalità

La tabella seguente riassume le funzionalità disponibili con questa release di Trident e le versioni di Kubernetes che supporta.

[cols="3"]
|===
| Caratteristica | Versione Kubernetes | Sono richiesti i feature gate? 


| Trident  a| 
1.27 - 1.34
 a| 
No



| Istantanee del volume  a| 
1.27 - 1.34
 a| 
No



| PVC da snapshot di volume  a| 
1.27 - 1.34
 a| 
No



| Ridimensionamento PV iSCSI  a| 
1.27 - 1.34
 a| 
No



| CHAP bidirezionale ONTAP  a| 
1.27 - 1.34
 a| 
No



| Politiche di esportazione dinamiche  a| 
1.27 - 1.34
 a| 
No



| Trident Operator  a| 
1.27 - 1.34
 a| 
No



| Topologia CSI  a| 
1.27 - 1.34
 a| 
No

|===


== Sistemi operativi host testati

Sebbene Trident non supporti ufficialmente sistemi operativi specifici, i seguenti sono noti per funzionare:

* Versioni di Red Hat Enterprise Linux CoreOS (RHCOS) supportate da OpenShift Container Platform su AMD64 e ARM64
* Red Hat Enterprise Linux (RHEL) 8 o versioni successive su AMD64 e ARM64
+

NOTE: NVMe/TCP richiede RHEL 9 o versioni successive.

* Ubuntu 22.04 LTS o successiva su AMD64 e ARM64
* Windows Server 2022
* SUSE Linux Enterprise Server (SLES) 15 o versioni successive


Per impostazione predefinita, Trident viene eseguito in un container e, pertanto, viene eseguito su qualsiasi worker Linux. Tuttavia, tali worker devono essere in grado di montare i volumi che Trident fornisce utilizzando il client NFS standard o l'iSCSI initiator, a seconda dei backend utilizzati.

L' `tridentctl`utility funziona anche su una qualsiasi di queste distribuzioni di Linux.



== Configurazione host

Tutti i nodi worker del cluster Kubernetes devono essere in grado di montare i volumi che hai fornito per i tuoi pod. Per preparare i nodi worker, è necessario installare NFS, iSCSI o gli strumenti NVMe in base alla selezione del driver.

link:../trident-use/worker-node-prep.html["Prepara il nodo worker"]



== Configurazione del sistema storage

Trident potrebbe richiedere modifiche a un sistema storage prima che una configurazione di backend possa utilizzarlo.

link:../trident-use/backends.html["Configura i backend"]



== Porte Trident

Trident richiede l'accesso a porte specifiche per la comunicazione.

link:../trident-reference/ports.html["Porte Trident"]



== Immagini dei container e versioni Kubernetes corrispondenti

Per le installazioni air-gapped, il seguente elenco è un riferimento delle immagini container necessarie per installare Trident. Usa il comando  `tridentctl images` per verificare l'elenco delle immagini container necessarie.



=== Immagini container necessarie per Trident 25.10

[cols="2"]
|===
| Versioni Kubernetes | Immagine container 


| v1.27.0, v1.28.0, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.34.0  a| 
* docker.io/netapp/trident:25.10.0
* docker.io/netapp/trident-autosupport:25.10
* registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
* registry.k8s.io/sig-storage/csi-attacher:v4.10.0
* registry.k8s.io/sig-storage/csi-resizer:v1.14.0
* registry.k8s.io/sig-storage/csi-snapshotter:v8.3.0
* registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.15.0
* docker.io/netapp/trident-operator:25.10.0 (opzionale)


|===