---
sidebar: sidebar 
permalink: trident-concepts/provisioning.html 
keywords: provisioning, Trident 
summary: Il provisioning in Trident si compone di due fasi principali. La prima fase associa una classe di storage al set di pool di storage back-end idonei e costituisce una necessaria preparazione prima del provisioning. La seconda fase include la creazione del volume vero e proprio e richiede la scelta di un pool di storage tra quelli associati alla classe di storage del volume in sospeso. 
---
= Provisioning
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il provisioning in Trident si compone di due fasi principali. La prima fase associa una classe di storage al set di pool di storage back-end idonei e costituisce una necessaria preparazione prima del provisioning. La seconda fase include la creazione del volume vero e proprio e richiede la scelta di un pool di storage tra quelli associati alla classe di storage del volume in sospeso.



== Associazione della storage class

L'associazione dei pool di storage back-end a una classe di storage si basa sia sugli attributi richiesti della classe di storage sia sui suoi  `storagePools`, `additionalStoragePools` e  `excludeStoragePools` elenchi. Quando crei una classe di storage, Trident confronta gli attributi e i pool offerti da ciascuno dei suoi back-end con quelli richiesti dalla classe di storage. Se gli attributi e il nome di un pool di storage corrispondono a tutti gli attributi e i nomi dei pool richiesti, Trident aggiunge quel pool di storage all'insieme dei pool di storage idonei per quella classe di storage. Inoltre, Trident aggiunge tutti i pool di storage elencati nell' `additionalStoragePools`elenco a quell'insieme, anche se i loro attributi non soddisfano tutti o nessuno degli attributi richiesti dalla classe di storage. Dovresti usare l' `excludeStoragePools`elenco per escludere e rimuovere i pool di storage dall'utilizzo per una classe di storage. Trident esegue un processo simile ogni volta che aggiungi un nuovo back-end, verificando se i suoi pool di storage soddisfano quelli delle classi di storage esistenti e rimuovendo quelli contrassegnati come esclusi.



== Creazione del volume

Trident utilizza quindi le associazioni tra classi di storage e pool di storage per determinare dove effettuare il provisioning dei volumi. Quando si crea un volume, Trident ottiene innanzitutto il set di pool di storage per la classe di storage di quel volume e, se si specifica un protocollo per il volume, Trident rimuove quei pool di storage che non possono fornire il protocollo richiesto (ad esempio, un backend NetApp HCI/SolidFire non può fornire un volume basato su file, mentre un backend ONTAP NAS non può fornire un volume basato su blocchi). Trident randomizza l'ordine di questo set risultante, per facilitare una distribuzione uniforme dei volumi, e quindi lo itera, tentando di effettuare il provisioning del volume su ciascun pool di storage a turno. Se riesce su uno, restituisce con successo, registrando eventuali errori riscontrati nel processo. Trident restituisce un errore *solo se* non riesce a effettuare il provisioning su *tutti* i pool di storage disponibili per la classe di storage e il protocollo richiesti.
